### ISSUE TITLE
A vexillologic "bug"

### ISSUE THREAD

**Issue by PabRod** [buntine/pioneers#2]
This is not a bug, but it is worth reporting:

The spanish flag used in the infographic for Ramón Llull was the national flag between 1843–1873 and 1874–1931. Provided Spain didn't existed as a nation in the times of Llull, I suggest using the aragonese flag or the current day spanish flag.

**Comment by buntine** [comment]
I had a feeling I'd got that one wrong! Haha Thanks.

**Comment by buntine** [comment]
Ok, I've used this one now: https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Flag_of_Aragon.svg/1000px-Flag_of_Aragon.svg.png

Is that correct?

**Comment by PabRod** [comment]
Oops... I don't think that's correct. That's the flag of modern day Aragón (administrative territory). Llull was born in the kingdom of Aragón ([flag](https://es.wikipedia.org/wiki/Corona_de_Arag%C3%B3n#/media/File:Si%C3%B1al_d%27Arag%C3%B3n.svg)).

I´ve seen that you also use the flag of modern day Germany, so maybe the best idea is just using the flag of modern day Spain ([here](https://en.wikipedia.org/wiki/Flag_of_Spain#/media/File:Flag_of_Spain.svg)) in order to follow the same scheme and avoiding bizarre and nerdish historiographic issues... like the one I opened! xD

**Comment by buntine** [comment]
Sorry! Yes, I decided for most of them to use the modern-day equivalents as I got myself confused a bunch of times trying to figure out which flag was correct. Europe has changed so many times over the past 1,000 years!

Ok, I will deploy with the modern day Spanish flag. Thanks again. :)
